<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tracemodel" nsURI="http://www.example.org/tracemodel" nsPrefix="tracemodel">
  <eClassifiers xsi:type="ecore:EClass" name="TraceModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeTraces" upperBound="-1"
        eType="#//NodeTrace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelTraces" upperBound="-1"
        eType="#//LabelTrace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowTraces" upperBound="-1"
        eType="#//FlowTrace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignmentTraces" upperBound="-1"
        eType="#//AssignmentTrace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dfdNode" lowerBound="1"
        eType="ecore:EClass ../../org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gdprProcessing" eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//Processing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1" eType="ecore:EClass ../../org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//Label"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelType" lowerBound="1"
        eType="ecore:EClass ../../org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//LabelType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assessmentFact" lowerBound="1"
        eType="ecore:EClass ../../mdpa.laf.referencemodel/model/LAF.ecore#//AssessmentFact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlow" lowerBound="1"
        eType="ecore:EClass ../../org.dataflowanalysis.dfd.dataflowdiagram/model/dataflowdiagram.ecore#//Flow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//Processing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" lowerBound="1" eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//Processing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//Data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignmentTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" lowerBound="1"
        eType="ecore:EClass ../../org.dataflowanalysis.dfd.datadictionary/model/datadictionary.ecore#//AbstractAssignment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputData" lowerBound="1"
        eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processing" lowerBound="1"
        eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//Processing"/>
  </eClassifiers>
</ecore:EPackage>
